#!/bin/bash

source paths

function sample_and_filename {
    local directory=$1
    local variant=$2
    if [ -d ${directory} ]
    then
        while IFS='' read -r -d '' path
        do
            local sample=$( basename $path | cut -f 1 -d . )
            echo $sample $path
        done < <( find ${directory} -type f -name "*.somatic.${variant}.vcf.gz" -print0)
    fi
}

sample_and_filename ${BROAD_DIR} snv_mnv | sort > tmp.snv.broad
sample_and_filename ${DKFZ_DIR} snv_mnv | sort > tmp.snv.dkfz
sample_and_filename ${SANGER_DIR} snv_mnv | sort > tmp.snv.sanger
sample_and_filename ${MUSE_DIR} snv_mnv | sort > tmp.snv.muse

join tmp.snv.broad tmp.snv.dkfz > tmp.snv.broad_dkfz
join tmp.snv.broad_dkfz tmp.snv.sanger > tmp.snv.broad_dkfz_sanger
join tmp.snv.broad_dkfz_sanger tmp.snv.muse > filelist.snv_mnv.txt
rm tmp.snv.{broad,dkfz,sanger,muse,broad_dkfz,broad_dkfz_sanger}

sample_and_filename ${BROAD_DIR} indel | sort > tmp.indel.broad
sample_and_filename ${DKFZ_DIR} indel | sort > tmp.indel.dkfz
sample_and_filename ${SANGER_DIR} indel | sort > tmp.indel.sanger

join tmp.indel.broad tmp.indel.dkfz > tmp.indel.broad_dkfz
join tmp.indel.broad_dkfz tmp.indel.sanger > filelist.indel.txt
rm tmp.indel.{broad,dkfz,sanger,broad_dkfz}
