#!/bin/bash
module load python/2.7.2
module load gcc/4.8.1 openblas python-packages/2
module load parallel

readonly ALLVARIANTS="snv_mnv indel_normed"
readonly DEFNJOBS=6

variants=${1:-$ALLVARIANTS}
NJOBS=${2:-$DEFNJOBS}

echo "Merging variants: ${variants}"

for variant in ${variants}
do
    mkdir -p results/${variant}/
    suffix="merged.somatic.${variant}.vcf"

    awk '{print $1}' filelist.${variant}.txt | \
        parallel -j ${NJOBS} ./analysis/merge_one_file {} ${variant} results/${variant}/{}.${suffix}
done
