#!/bin/bash
readonly SAMPLE=$1
readonly USAGE="Usage: $0 sample-id"
readonly VARIANT=indel

source paths

if [ -z ${SAMPLE} ] 
then
    >&2 echo "${USAGE}"
    >&2 echo "  normalizes all indel variant files corresponding to the sample"
    >&2 echo "invocation: $0 $1 $2 $3"
    exit
fi

readonly line=$( ./analysis/filenames-from-sample.sh ${SAMPLE} ${VARIANT} )
IFS=' ' read -r -a filenames <<< "${line}"
readonly broadfile=${filenames[0]}
readonly dkfzfile=${filenames[1]}
readonly sangerfile=${filenames[2]}

function normalize {
    local in_vcf=$1
    bcftools norm -c w -m -indels -O v -f ${REFERENCE} ${in_vcf} 2>> norm.errs.txt
}

function newfilename {
    local in_vcf=$1
    base=$( basename $in_vcf )
    new=${base/indel/indel_normed}
    echo ${new/.gz/}
}

function zip_and_index {
    local dir=$1
    local vcf=$2

    ( cd $dir; bgzip $vcf; tabix -p vcf ${vcf}.gz )
}

output=""

# broad - deal with the fact that the format fields are absent
#  and bcftools and mergevcf don't handle that in the same way

broadnormedfile=$( newfilename ${broadfile} )
if [ ! -f ${NORMED_INDEL_DIR}/${broadnormedfile}/gz ] 
then
    normalize <( zcat ${broadfile} | sed -e 's/		$/	.	.	./' ) \
        | sed -e '/^[^#]/s/	[^	]*	[^	]*	[^	]*$//' \
        > ${NORMED_INDEL_DIR}/${broadnormedfile}
    zip_and_index $NORMED_INDEL_DIR ${broadnormedfile}
    output="true"
fi

# dkfz - pretty well behaved

dkfznormedfile=$( newfilename ${dkfzfile} )
if [ ! -f ${NORMED_INDEL_DIR}/${dkfznormedfile}.gz ]
then
    normalize ${dkfzfile} \
        > ${NORMED_INDEL_DIR}/${dkfznormedfile}
    zip_and_index $NORMED_INDEL_DIR ${dkfznormedfile}
    output="true"
fi

# sanger - has that one header line that ends in '='

sangernormedfile=$( newfilename $sangerfile )
if [ ! -f ${NORMED_INDEL_DIR}/${sangernormedfile}.gz ]
then
    normalize ${sangerfile} | grep -v "=$" \
        > ${NORMED_INDEL_DIR}/${sangernormedfile}
    zip_and_index $NORMED_INDEL_DIR ${sangernormedfile}
    output="true"
fi

if [ $output == "true" ]
then
    echo "${SAMPLE} ${NORMED_INDEL_DIR}/${broadnormedfile}.gz ${NORMED_INDEL_DIR}/${dkfznormedfile}.gz ${NORMED_INDEL_DIR}/${sangernormedfile}.gz"
fi
